### ISSUE TITLE
Deprecated gunicorn command

### ISSUE THREAD

**Issue by tzenderman** [lionheart/django-template#1]
The gunicorn_django command used in the supervisor conf (https://github.com/lionheart/django-template/blob/django-1.6/conf/supervisor/production.ini#L2) was deprecated in gunicorn==18.0: http://docs.gunicorn.org/en/18.0/news.html

I think the equivalent command would be:

```
/home/ubuntu/environments/{{ project_name }}/bin/gunicorn wsgi:application -c /var/www/{{ project_name }}/conf/gunicorn/current.py
```

**Comment by dlo** [comment]
Thanks, good find! Just fixed in 02e3efd.

**Comment by tzenderman** [comment]
No worries, glad I could help! I already got burned by this one!

**Comment by dlo** [comment]
Yikes, sorry! No idea how this stuck around, given that gunicorn 18's been out for a while. Specifying the version number in the requirements too in case the command line changes again.
