### ISSUE TITLE
Add PostgreSQL setup instructions

### ISSUE THREAD

**Issue by dlo** [lionheart/django-template#3]

**Comment by eolszewski** [comment]
@dlo does this assume they already have psql? How thorough do we need to be here?

**Comment by dlo** [comment]
Hmm, good question. I think the safest route would be to assume they don't. I think a mention of Homebrew + "brew install postgresql" for OS X is enough. We're probably OK pointing Linux users to https://wiki.postgresql.org/wiki/Detailed_installation_guides.

**Comment by dlo** [comment]
:sparkles: !
